services:
  - type: web
    name: mar-os
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_CLICKUP_TOKEN
        sync: false
